reduce severity of log to info in case of flush on non-existing member
allas-nvidia/sonic-swss pull request #3
Opened 2021-02-23 17:12 UTC by allas-nvidia

Signed-off-by: allas <allas@nvidia.com>

**What I did**
Reduced severity of log to info in case of flush on non-existing member.

**Why I did it**
There is a race in the infra which can cause the scenario, when we receives notifications about FDB FLUSH on port which was already removed.

**How I verified it**
    >  sudo config vlan add 3
    >  sudo config vlan member add 3 Ethernet8
    >  sudo config vlan member del 3 Ethernet8

**Details if related**

2021-02-25 12:26 UTC, noaOrMlnx requested changes

2021-02-25 12:26 UTC, noaOrMlnx commented on orchagent/fdborch.cpp
> +
remove extra line

2021-02-25 12:26 UTC, noaOrMlnx commented on orchagent/fdborch.cpp
> +
remove extra line

2021-02-25 12:53 UTC, stepanblyschak commented on orchagent/fdborch.cpp
> +            /*in case of flush - can be ignore due to a race*/
If there is such a comment there should be more description about the race

2021-02-28 14:28 UTC, liat-grozovik reviewed
@stepanblyschak isnt it a discussion we need to do with Kamil before publishing a PR?

2021-03-01 10:39 UTC, stepanblyschak approved these changes

2021-03-01 10:41 UTC, stepanblyschak commented
@liat-grozovik talked with Alla, I can raise this race on tommorows meeting with MSFT and we can discuss.

2021-03-01 10:49 UTC, stepanblyschak commented
@allas-nvidia This PR hides the error but need to discuss with MSFT whether there is fundamentally something wrong in the flow or wether this change can be accepted and FDB_FLUSH can be ignored for non existing port. Could you please create a github issue describing the race - that will support our discussion with MSFT.

2021-03-02 13:34 UTC, liat-grozovik commented
@allas-nvidia do we have github issue on the race? We will need it today pls

2021-03-03 17:12 UTC, dprital commented
@allas-nvidia  please run CI and lets move toward External PR

2021-03-09 10:30 UTC, liat-grozovik commented on orchagent/fdborch.cpp
> +            /*in case of flush - can be ignored due to a race*/
please have space before /* and */

2021-03-09 14:35 UTC, liat-grozovik approved these changes

2021-03-10 18:31 UTC, closed without merging